#!/usr/bin/env python3
"""One markdown report over every ablation result file that exists.

WHY
    There are now five result files (published, Run B, Run B seed-2, Run C, freeze
    sweep) and the question that matters spans all of them: does layer_freeze beat
    full_finetune, and is the answer stable? Reading five JSONs by hand is how the
    17%/83% and 0-19 discrepancies survived into the manuscript in the first place.

    Writes results/FINAL_COMPARISON.md so it can be read after a `farm.ps1 pull`
    without a Python environment.

Everything here is read-only. It never trains and never writes into models/.
"""
import json
from pathlib import Path

ROOT = Path("/raid/session/aicontents/farm")
OUT = ROOT / "results" / "FINAL_COMPARISON.md"

# label -> (relative path, what changed vs the published run)
RUNS = [
    ("published", "results/ablation_comprehensive.json",
     "original splits (37% train/test leakage), seed 42"),
    ("runB", "results/RUNB_ablation.json",
     "deduped split, seed 42 - leakage is the only change"),
    ("runB2", "results/RUNB2_ablation.json",
     "deduped split, seed 1337 - seed is the only change vs runB"),
    ("freeze0", "results/FREEZE0_ablation.json",
     "deduped split, seed 42, freeze_layers=0 (embedding table only)"),
    ("runC", "results/RUNC_ablation.json",
     "deduped split, seed 42, MINED hard negatives"),
]


def rows_of(p):
    d = json.load(open(p, encoding="utf-8"))
    return d.get("results", d if isinstance(d, list) else [])


def sl(r, side, k):
    return r[f"{side}_metrics"]["service_level"][k]


def collect():
    out = {}
    for label, rel, note in RUNS:
        p = ROOT / rel
        if not p.exists():
            out[label] = (None, rel, note)
            continue
        try:
            out[label] = (rows_of(p), rel, note)
        except Exception as e:                      # noqa: BLE001 - report, never crash
            out[label] = (None, f"{rel}  (unreadable: {e})", note)
    return out


def main():
    data = collect()
    L = []
    w = L.append

    w("# FARM Stage 1 - all runs compared\n")
    w("Generated by `jobs/compare_all.py`. Every row is measured, none is copied "
      "from the manuscript.\n")

    # ---------- 1. what exists ----------
    w("## Runs present\n")
    w("| run | file | what changed |")
    w("|---|---|---|")
    for label, rel, note in RUNS:
        rows = data[label][0]
        state = f"{len(rows)} methods" if rows else "**missing**"
        w(f"| `{label}` | `{rel}` ({state}) | {note} |")
    w("")

    # ---------- 2. full table ----------
    w("## Service-level results\n")
    w("| run | method | trainable | trig R@1 | act R@1 | joint R@1 | joint R@5 |")
    w("|---|---|---:|---:|---:|---:|---:|")
    for label, rel, _ in RUNS:
        rows = data[label][0]
        if not rows:
            continue
        for r in rows:
            pct = r.get("trainable_pct")
            pct_s = f"{pct:.1f}%" if isinstance(pct, (int, float)) else "-"
            w(f"| {label} | {r.get('method','?')} | {pct_s} | "
              f"{sl(r,'trigger','R@1'):.3f} | {sl(r,'action','R@1'):.3f} | "
              f"{sl(r,'joint','R@1'):.3f} | {sl(r,'joint','R@5'):.3f} |")
    w("")

    # ---------- 3. the claim under test ----------
    w("## The claim under test: layer_freeze vs full_finetune\n")
    w("The paper's Stage 1 contribution is that selective layer freezing beats full "
      "fine-tuning. A positive delta supports it; a negative delta contradicts it.\n")
    w("| run | full_finetune | layer_freeze | delta | supports paper? |")
    w("|---|---:|---:|---:|---|")
    verdicts = {}
    for label, _, _ in RUNS:
        rows = data[label][0]
        if not rows:
            continue
        ff = next((r for r in rows if r.get("method") == "full_finetune"), None)
        lf = next((r for r in rows if r.get("method") == "layer_freeze"), None)
        if not (ff and lf):
            continue
        a, b = sl(ff, "joint", "R@1"), sl(lf, "joint", "R@1")
        d = b - a
        verdicts[label] = d
        w(f"| {label} | {a:.3f} | {b:.3f} | {d:+.3f} | "
          f"{'YES' if d > 0 else 'NO'} |")
    w("")
    if verdicts:
        pos = [k for k, v in verdicts.items() if v > 0]
        neg = [k for k, v in verdicts.items() if v <= 0]
        w(f"- supports freezing: {', '.join(pos) if pos else 'none'}")
        w(f"- contradicts freezing: {', '.join(neg) if neg else 'none'}")
        if "runB" in verdicts and "runB2" in verdicts:
            same = (verdicts["runB"] > 0) == (verdicts["runB2"] > 0)
            spread = abs(verdicts["runB"] - verdicts["runB2"])
            w(f"- **seed check**: runB {verdicts['runB']:+.3f} vs runB2 "
              f"{verdicts['runB2']:+.3f} (spread {spread:.3f}). "
              f"Sign is {'STABLE - the inversion is real' if same else 'UNSTABLE - within seed noise, do not report either direction as a finding'}.")
        if "freeze0" in verdicts:
            w(f"- **capacity check**: at freeze_layers=0 (embedding table only) the "
              f"delta is {verdicts['freeze0']:+.3f}. If this is positive while "
              f"freeze_layers=12 is negative, the useful mechanism is freezing the "
              f"EMBEDDING TABLE, not freezing transformer layers - which is a "
              f"sharper claim than the paper currently makes.")
    w("")

    # ---------- 4. lift ----------
    w("## Lift over independence\n")
    w("`lift = joint_R@1 - (trigger_R@1 x action_R@1)`. Zero means trigger and action "
      "are selected independently, i.e. no compatibility modelling is happening.\n")
    w("| run | method | trig | act | product | joint | lift |")
    w("|---|---|---:|---:|---:|---:|---:|")
    for label, _, _ in RUNS:
        rows = data[label][0]
        if not rows:
            continue
        for r in rows:
            if r.get("method") != "full_finetune":
                continue
            t, a = sl(r, "trigger", "R@1"), sl(r, "action", "R@1")
            j = sl(r, "joint", "R@1")
            w(f"| {label} | full_finetune | {t:.3f} | {a:.3f} | {t*a:.3f} | "
              f"{j:.3f} | {j-t*a:+.3f} |")
    w("")
    w("Run C is the controlled test of mined hard negatives: if lift stays ~0 there "
      "too, that is a legitimate negative result and the cross-schema claim in "
      "`3-approach.tex:226` needs to be rewritten rather than re-run.\n")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(L), encoding="utf-8")
    print("\n".join(L))
    print(f"\n\nwrote {OUT}")


if __name__ == "__main__":
    main()
